version: 2

builds:
  - binary: snipe
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: onurogut
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/onurogut/snipe"
    description: "Kill processes by port"
    license: "MIT"
    install: |
      bin.install "snipe"

scoops:
  - repository:
      owner: onurogut
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/onurogut/snipe"
    description: "Kill processes by port"
    license: "MIT"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
